# Generated by Django 3.0.7 on 2020-07-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='items_json',
            new_name='itemsjson',
        ),
    ]
